version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: 'symfony/*'
        update-types:
          - version-update:semver-major
    groups:
      symfony:
        patterns:
          - 'symfony/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly