when@prod: &security_prod
    security:
        # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        providers:
            hwi:
                id: hwi_oauth.user.provider.entity_failsafe
            firewalls:
                main:
                    lazy: true
                    provider: hwi
                    oauth:
                        resource_owners:
                            google: "/login/check-google"
                        login_path: /login
                        use_forward: false
                        failure_path: /login
                        default_target_path: /
                        oauth_user_provider:
                            service: hwi_oauth.user.provider.entity_failsafe
                    logout:
                        path: app_logout
                        target: /
                    entry_point: 'hwi_oauth.authentication.entry_point.oauth.main'

when@dev: &security_dev
    security:
        providers:
            hwi:
                id: hwi_oauth.user.provider.entity_failsafe
        firewalls:
            main:
                lazy: true
                provider: hwi
                oauth:
                    resource_owners:
                        google: "/login/check-google"
                    login_path: /login
                    use_forward: false
                    failure_path: /login
                    default_target_path: /
                    oauth_user_provider:
                        service: hwi_oauth.user.provider.entity_failsafe
                logout:
                    path: app_logout
                    target: /
                entry_point: 'hwi_oauth.authentication.entry_point.oauth.main'
                custom_authenticators:
                    - App\Service\Security\Dev\FakeApiKeyAuthenticator

when@test: *security_dev